### ISSUE TITLE
Add more html in index.html

### ISSUE THREAD

**Issue by Rehan-stack** [Rehan-stack/github_practice#2]

**Comment by YaseenEjaz02** [comment]
<!DOCTYPE html>
<html>
  <head>
    <title>Testing HTML</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
    <p>This is a test HTML file.</p>
     <ul>
      <li>Item 1</li>
      <li>Item 2</li>
      <li>Item 3</li>
    </ul>
  </body>
</html>

**Comment by Rehan-stack** [comment]
Completed
